name: superhero_talks
ddescription: A new Flutter project.


publish_to: 'none'

version: 1.0.6+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_speed_dial: ^1.0.9
  http: ^0.12.2
  image_downloader: ^0.20.1
  hive: ^1.4.4+1
  path_provider: any
  esys_flutter_share:
  flutter_cache_manager: ^2.1.2
  wallpaper_manager: "^1.0.10"
  carousel_slider: ^3.0.0
  cached_network_image: any
  permission_handler: any
  url_launcher:
  firebase_admob: 
  new_version: ^0.0.6
  firebase_messaging: 


  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: "^0.8.0"
  flutter_native_splash: ^0.3.0

flutter_native_splash:
  image: assets/logo/splash.png
  color: "#ffffff"
  
  
flutter_launcher_name:
  name: "SuperHero Talks - Wallpaper App"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/superherotalks.png"

  #integration_test:
   # sdk: flutter


flutter:


  uses-material-design: true

  
  assets:
    - assets/logo/

  
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
